### PR TITLE
Enable FUSE passthrough and  others

### PR DESCRIPTION
**Pull request by neobuddy89**

### CODE REVIEW

**Comment by chiteroman** [comment]
@neobuddy89 Why remove sdcardfs? FUSE and emulated_storage gives a lot of problems to users, games doesn't work and users can't restore backups. It's better to use sdcardfs and EROFS for odm and vendor like @SebaUbuntu did: https://github.com/xiaomi-sm8150-devs/android_device_xiaomi_sm8150-common/commit/50e9bd0d44caf12bb0c84d48332a2dc4b1df238f

I'm testing this kernel with more changes and it works pretty well: https://github.com/chiteroman/kernel_vayu

**Comment by SebaUbuntu** [comment]
🍚 + casefolding requires a data format

**Comment by neobuddy89** [comment]
all new devices have it enabled
https://source.android.com/docs/core/storage/fuse-passthrough

All required is one-time format. :)
But it's maintainer call.

**Comment by neobuddy89** [comment]
Also xiaomi sm6150 devices switched to this.

**Pull request closed without merging**
